### ISSUE TITLE
0.2.1 release checklist

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-bespokefit#246]
- [x] Pre-release PR
    - [x] Update releasehistory (Just autogenerate with the release, then put it in readme.md
- [x] Make the release with autogenerated docs (I guess remove the pre-release PR entry)
- [x] conda-forge PR
    - [x] Check for updated deps from changes to test envs
    - [x]   - geometric >=1
    - [x] Up-pin force balance
    - [x] Down-pin pydantic
    - [x] Up-pin qcelemental, qcengine
    - [x] Explicitly add openff-units, openff-interchange
    - [x] Re-render
- [x] Trigger RTD builds of new version (if needed)
- [ ] Check deployment tests
- [ ] Wait a week and then make a public announcement in #general or something
