### ISSUE TITLE
0.2.2 release checklist

### ISSUE THREAD

**Issue by Yoshanuikabundi** [openforcefield/openff-bespokefit#261]
- [x] Pre-release PR
    - [x] Update releasehistory (Just autogenerate with the release, then put it in readme.md
- [x] Make the release with autogenerated docs (I guess remove the pre-release PR entry)   
    - https://github.com/openforcefield/openff-bespokefit/releases/tag/0.2.2
- [x] conda-forge PR
    - https://github.com/conda-forge/openff-bespokefit-feedstock/pull/15
    - [x] Check for updated deps from changes to test envs
    - [x] Re-render
- [x] Check that RTD has built new version and updated `stable`
- [ ] Check deployment tests
